= Apache Causeway - Laboratory
:toc:
:toc-title: pass:[<h3>Contents</h3>]
:toc-placement!:

Laboratory for the _Apache Causeway_ framework. (Tutorials, Experiments, ...)
____
http://causeway.apache.org[Apache Causeway] software is a framework for rapidly developing domain-driven apps in Java.
Write your business logic in entities, domain services and repositories, and the framework dynamically generates a representation of that domain model as a webapp or a RESTful API.
____

toc::[]

== Tutorials

* xref:adoc/spring-data-with-apache-causeway-get-started.adoc[Sample Application with Spring Boot and Apache Causeway]
* xref:adoc/secman-get-started.adoc[Sample Application using Apache Causeway SecMan Extension]

== Experiments

* `cssgridlayout` - _Vaadin_ with _CSS Grid Layout_.
* `multischema` - _Spring Data JPA_ with multiple database schemas.
* `springsecurity` _Spring_ application with _GitHub_ as an _OpenId Connect_ provider. 
* `vaadin` - How to package _Vaadin_ fronted as _Maven_ artifact, so it can be consumed as a library. 
